### ISSUE TITLE
[Bug] Antilink not deleting links

### ISSUE THREAD

**Issue by ghost** [Kowlin/refactored-cogs#35]
- Cog:
Antilink
- Issue description:
Not deleting links
- Reproduction Steps:
Well, I don't know.
- Traceback of error (Console):
```
Traceback (most recent call last):
  File "lib\discord\ext\commands\bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\Other Program\Red-DiscordBot\cogs\antilink.py", line 139, in _new_message
    if message.channel.id in self.json[message.server.id]['excluded_channels']:
KeyError: 'excluded_channels'
Ignoring exception in message
Traceback (most recent call last):
  File "lib\discord\ext\commands\bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\Other Program\Red-DiscordBot\cogs\antilink.py", line 139, in _new_message
    if message.channel.id in self.json[message.server.id]['excluded_channels']:
KeyError: 'excluded_channels'
```

**Comment by xXFireBunnyXx** [comment]
that error is because 'excluded_channels' is missing from your antilink.json

**Comment by Kowlin** [comment]
Sorry for the late response, but this can be solved by adding and removing a excluded channel. I've got a patch that addresses this that I will push later today.
