### ISSUE TITLE
antilinkset togglestrict shows 'Error in command'

### ISSUE THREAD

**Issue by Skyridr** [Kowlin/refactored-cogs#36]
When using !antilinkset togglestrict, the following console error is being printed:

> [21/09/2017 11:41] ERROR red on_command_error 369: Exception in command 'antilinkset togglestrict'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/Red/cogs/antilink.py", line 61, in togglestrict
    if self.json[serverid]['strict'] is True:
KeyError: 'strict'

Ubuntu 16.04, Python 3.5.

Regards,
Skyrider

**Comment by Skyridr** [comment]
1 month later, no responds?

**Comment by skeith** [comment]
I am so surprised you did not try to see his channel on Cog Server. Here let me paste his announcement
```

ANOUNCEMENT:

I currently do not support any of my cogs due to my work on Red v3 and personal projects. If you're still using my stuff magicly enough, congratulations, you've made it further then most people have with my stuff.
```

**Comment by Skyridr** [comment]
I actually missed that, though that was posted 3 days ago. Did mention this issue a month ago ^^, but quite a shame it's no longer supported.

**Comment by skeith** [comment]
>Did mention this issue a month ago ^^, but quite a shame it's no longer supported.

Didn't you read `I currently do not support any of my cogs due to my work on Red v3 and personal projects`

He makes it clear long before his official announcement and muting the channel and also, if you read this GH readme, `For support see the wiki or the support server`, he clearly wish you go to cog support server for faster support. If you just did that a month ago, you might have answer earlier and won't missed his announcement
